# Site settings
name: 'Lost Eden'
description: "Bienvenue sur le site dédié à l'imaginaire, Lost Eden. Ce site fait suite au fanzine Lost Eden créé en 1997. Il a pour vocation de traiter de l’actualité de l'imaginaire et du rêve à travers l’animation japonaise et la musique."
meta_description: "Lost Eden, chroniqueurs de l'imaginaire depuis 1997"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl:
production_url: https://losteden.fr/

# Authors
authors: {
  'Erwan': {
    'name': 'Erwan',
    'image': 'erwan.jpg',
    'bio': "J'étais le rédacteur en chef du fanzine Lost Eden. Je souhaitais depuis longtemps mettre en ligne tous les articles des 6 numéros qui ont été créés de 1997 à 2000."
  },
    'Motenai': {
    'name': 'Motenaï',
    'image': 'motenai.jpg',
    'bio': "Rédacteur dans Lost Eden depuis le numéro 2."
  },
   'Kaori': {
    'name': 'Kaori',
    'image': 'kaori.jpg',
    'bio': "Rédactrice dans Lost Eden depuis le numéro 2."
  },
  'Ronin': {
    'name': 'Le Ronin',
    'image': 'leronin.jpg',
    'bio': "Rédacteur dans Lost Eden depuis le numéro 4."
  },
  'Natalie': {
    'name': 'Natalie',
    'image': 'natalie.jpg',
    'bio': "Rédactrice dans Lost Eden depuis le numéro 4."
  },
  'Emilie': {
    'name': 'Emilie',
    'image': 'emilie.jpg',
    'bio': "Rédactrice dans Lost Eden depuis le numéro 5."
  }
}

# Contact form setings
email: erwan.carriou@mac.com
contact_page_description: "Pour envoyer un message à l'équipe, compléter le formulaire suivant:"
thankyou_page_description: "Votre message a bien été envoyé!"

# Social links
twitter: 
github:

# Navigation
navigation:
  - text: Dossiers
    url: /tag/dossier/index.html
  - text: Anime
    url: /tag/anime/index.html
  - text: Musique
    url: /tag/musique/index.html
  - text: Chroniques
    url: /tag/chronique/index.html
  - text: Fanzines
    url: /fanzines.html
  - text: Contacts
    url: /contact.html

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
